package main;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.Grafos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class Ventana extends javax.swing.JFrame {

    public static Grafos g;
    public static String direccion_archivo;
    private Grafos grafo;

    /**
     * Creates new form Ventana
     */
    public Ventana(Grafos grafos, String direccion) throws IOException {
        initComponents();
        this.setVisible(true);

        ArchivoTxt a = new ArchivoTxt();
        g = a.LectorChooser(grafos);
       direccion_archivo = direccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        users = new javax.swing.JButton();
        relaciones = new javax.swing.JButton();
        graficar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setText("Buscar Archivo");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        users.setText("Usuarios");
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        relaciones.setText("Relaciones");
        relaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacionesActionPerformed(evt);
            }
        });
        jPanel1.add(relaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        graficar.setText("Graficar");
        graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarActionPerformed(evt);
            }
        });
        jPanel1.add(graficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -5, 640, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void relacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacionesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ventana3 v3 = new Ventana3(g, direccion_archivo);

    }//GEN-LAST:event_relacionesActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ventana_2 v1 = new Ventana_2(g, direccion_archivo);

    }//GEN-LAST:event_usersActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            Ventana n = new Ventana(this.grafo, direccion_archivo);
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArchivoTxt archivoTxt = new ArchivoTxt();
        try {
            
            g = archivoTxt.LectorChooser(g);
  
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_buscarActionPerformed

    private void graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarActionPerformed
      try {
          GraficarG graficarG = new GraficarG();
        graficarG.graficar(g);} catch(Exception e){
          System.out.println(e); 
        }
    }//GEN-LAST:event_graficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ventana(g, direccion_archivo).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton graficar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton relaciones;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables
}
